- type: latheRecipe
  id: SpeedLoaderSpecial
  result: SpeedLoaderSpecial
  categories:
  completetime: 5
  materials:
    Steel: 200

- type: latheRecipe
  id: MagazinePistolSpecial
  result: MagazinePistolSpecial
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 100

- type: latheRecipe
  id: CartridgeSpecial
  result: CartridgeSpecial
  categories:
  - Ammo
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeSpecialIncendiary
  result: CartridgeSpecialIncendiary
  categories:
  - Ammo
  completetime: 2
  materials:
    Plastic: 20

- type: latheRecipe
  id: CartridgeSpecialUranium
  result: CartridgeSpecialUranium
  categories:
  - Ammo
  completetime: 2
  materials:
    Plastic: 20
    Uranium: 10

- type: latheRecipe
  id: CartridgeSpecialHoly
  result: CartridgeSpecialHoly
  categories:
  - Ammo
  completetime: 2
  materials:
    Steel: 15
    Silver: 5

- type: latheRecipe
  id: CartridgeSpecialMindbreaker
  result: CartridgeSpecialMindbreaker
  categories:
  - Ammo
  completetime: 2
  materials:
    Plastic: 15
    Steel: 5
    Bluespace: 5

- type: latheRecipe
  id: MagazineBoxSpecial
  result: MagazineBoxSpecial
  categories:
  - Ammo
  completetime: 5
  materials:
    Steel: 1250

- type: latheRecipe
  id: MagazineBoxSpecialPractice
  result: MagazineBoxSpecialPractice
  categories:
  - Ammo
  completetime: 5
  materials:
    Plastic: 1200

- type: latheRecipe
  id: MagazineBoxSpecialIncendiary
  result: MagazineBoxSpecialIncendiary
  categories:
  - Ammo
  completetime: 5
  materials:
    Plastic: 1250

- type: latheRecipe
  id: MagazineBoxSpecialUranium
  result: MagazineBoxSpecialUranium
  categories:
  - Ammo
  completetime: 5
  materials:
    Plastic: 1250
    Uranium: 125

- type: latheRecipe
  id: MagazineBoxSpecialMindbreaker
  result: MagazineBoxSpecialMindbreaker
  categories:
  - Ammo
  completetime: 5
  materials:
    Plastic: 1250
    Steel: 75
    Bluespace: 75

- type: latheRecipe
  id: ClothingOuterArmorPlateCarrier
  result: ClothingOuterArmorPlateCarrier
  completetime: 10
  materials:
    Steel: 1500
    Plastic: 1500

- type: latheRecipe
  id: ClothingOuterArmorDuraVest
  result: ClothingOuterArmorDuraVest
  completetime: 10
  materials:
    Steel: 500
    Plastic: 1000

- type: latheRecipe
  id: WeaponEnergyGun
  result: WeaponEnergyGun
  categories:
  - Weapons
  completetime: 8
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  id: WeaponEnergyGunMini
  result: WeaponEnergyGunMini
  categories:
  - Weapons
  completetime: 4
  materials:   #Half of Energy Gun Recipe
    Steel: 1000
    Glass: 400
    Plastic: 250

- type: latheRecipe
  id: WeaponEnergyGunPistol
  result: WeaponEnergyGunPistol
  categories:
  - Weapons
  completetime: 10
  materials:
    Steel: 1500
    Glass: 600
    Plastic: 400
    Gold: 150

- type: latheRecipe
  id: WeaponGunLaserCarbineAutomatic
  result: WeaponGunLaserCarbineAutomatic
  categories:
  - Weapons
  completetime: 15
  materials:
    Steel: 2000
    Glass: 1000
    Plastic: 500
    Gold: 250
    Silver: 100
    Plasma: 500
