- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
    - !type:CharacterEmployerRequirement
      employers:
      - NanoTrasen
      - IdrisIncorporated
  weight: 10 # DeltaV - Changed HoP weight from 20 to 10 due to them not being more important than other Heads
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel # WD EDIT
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  # Delta V - fuck all of this HoP is a service role
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security # NoooOoOo!! My HoPcurity!1
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  - Boxer # WD EDIT
  - Clown # WD EDIT
  - Library # WD EDIT
  - Mime # WD EDIT
  - Musician # WD EDIT
  - Reporter # WD EDIT
  - Zookeeper 
  # WD EDIT  START
  - Quartermaster
  - Mail
  - Paramedic
  - Psychologist
  - Corpsman
  # WD EDIT END
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: HoPGear
  subGear:
  - HoPPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackHOPFilled
    shoes: ClothingShoesLeather # DeltaV - HoP needs something better than plebe shoes.
    id: HoPPDA
    ears: ClothingHeadsetHoP # DeltaV - HoP is now a service role, replaces their all channels headset.
  innerClothingSkirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelHOPFilled
  duffelbag: ClothingBackpackDuffelHOPFilled

- type: startingGear
  id: HoPPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitHoP
    head: ClothingHeadEnvirohelmHoP
    gloves: ClothingHandsGlovesEnviroglovesHoP
