- type: entity
  parent: CrateSecgear
  id: CrateSecurityGrenadeBarrier
  name: grenade barrier crate
  description: Contains four barrier grenades. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: GrenadeBarrier
        amount: 4

- type: entity
  id: CrateArmoryMosin
  parent: CrateWeaponSecure
  components:
  - type: StorageFill
    contents:
    - id: WeaponSniperMosin
      amount: 3
    - id: BoxSpeedLoaderLightRifle
