- type: entity
  name: handcuff box
  parent: BoxPlastic # WWDP edit
  id: BoxHandcuff
  description: A box full of handcuffs.
  components:
  - type: StorageFill
    contents:
      - id: Handcuffs
        amount: 4
  - type: Sprite
    layers:
    - state: bg # WWDP edit start
    - state: handcuff
      sprite: _White/Objects/Storage/boxes_icon.rsi
    - state: box_plastic_rib_grey_base
    - state: box_plastic_sec
      map: [ top ]
  - type: GenericVisualizer
    visuals:
      enum.StorageVisuals.Open:
        top:
          True: { state: box_plastic_sec_open }
          False: { state: box_plastic_sec } # WWDP end

- type: entity
  name: prisoner headset box
  parent: BoxPlastic # WWDP edit
  id: BoxPrisonerHeadset
  description: A box of prisoner headsets.
  components:
  - type: StorageFill
    contents:
    - id: ClothingHeadsetPrison
      amount: 4
  - type: Sprite
    layers:
    - state: bg # WWDP edit start
    - state: headset
      sprite: _White/Objects/Storage/boxes_icon.rsi
    - state: box_plastic_rib_grey_base
    - state: box_plastic_chem
      map: [ top ]
  - type: GenericVisualizer
    visuals:
      enum.StorageVisuals.Open:
        top:
          True: { state: box_plastic_chem_open }
          False: { state: box_plastic_chem } # WWDP end

- type: entity
  name: flashbang box
  parent: BoxSteel # WWDP edit
  id: BoxFlashbang
  description: 'WARNING: These devices are extremely dangerous and can cause blindness or deafness in repeated use.'
  components:
  - type: StorageFill
    contents:
      - id: GrenadeFlashBang
        amount: 4
  - type: Sprite
    layers:
    - state: bg # WWDP edit start
    - state: flashbang
      sprite: _White/Objects/Storage/boxes_icon.rsi
    - state: box_steel_rib_base
    - state: box_steel_sec
      map: [ top ]
  - type: GenericVisualizer
    visuals:
      enum.StorageVisuals.Open:
        top:
          True: { state: box_steel_sec_open }
          False: { state: box_steel_sec } # WWDP end

- type: entity
  name: sechud box
  parent: BoxPlastic # WWDP edit
  id: BoxSechud
  description: A box of security glasses.
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity # WD SecHuds
        amount: 4
  - type: Sprite
    layers:
    - state: bg # WWDP edit start
    - state: sechud
      sprite: _White/Objects/Storage/boxes_icon.rsi
    - state: box_plastic_rib_grey_base
    - state: box_plastic_sec
      map: [ top ]
  - type: GenericVisualizer
    visuals:
      enum.StorageVisuals.Open:
        top:
          True: { state: box_plastic_sec_open }
          False: { state: box_plastic_sec } # WWDP end

- type: entity
  name: ziptie box
  parent: BoxPlastic # WWDP edit
  id: BoxZiptie
  description: A box full of zipties.
  components:
  - type: StorageFill
    contents:
      - id: Zipties
        amount: 10
  - type: Sprite
    layers:
    - state: bg # WWDP edit start
    - state: ziptie
      sprite: _White/Objects/Storage/boxes_icon.rsi
    - state: box_plastic_rib_grey_base
    - state: box_plastic_sec
      map: [ top ]
  - type: GenericVisualizer
    visuals:
      enum.StorageVisuals.Open:
        top:
          True: { state: box_plastic_sec_open }
          False: { state: box_plastic_sec } # WWDP end

- type: entity
  name: forensic pad box
  parent: BoxPlastic # WWDP edit
  id: BoxForensicPad
  description: A box of forensic pads.
  components:
  - type: StorageFill
    contents:
    - id: ForensicPad
      amount: 9
  - type: Sprite
    layers:
    - state: bg # WWDP edit start
    - state: forensic
      sprite: _White/Objects/Storage/boxes_icon.rsi
    - state: box_plastic_rib_grey_base
    - state: box_plastic_sec
      map: [ top ]
  - type: GenericVisualizer
    visuals:
      enum.StorageVisuals.Open:
        top:
          True: { state: box_plastic_sec_open }
          False: { state: box_plastic_sec } # WWDP end
