- type: entity
  name: cleanades box
  parent: BoxSteel # WWDP edit
  id: BoxCleanerGrenades
  description: A box full of cleanades.
  components:
  - type: StorageFill
    contents:
      - id: CleanerGrenade
        amount: 4
  - type: Sprite
    layers:
    - state: box_steel_rib_base # WWDP edit start
    - state: bg
      map: [ paper ]
      sprite: _White/Objects/Storage/boxes_icon.rsi
    - state: flashbang
      map: [ label ]
      sprite: _White/Objects/Storage/boxes_icon.rsi
    - state: box_steel
      map: [ top ] # WWDP end

#- type: entity
#  name: NT "AgriChem Is Fun" kit
#  parent: BoxCardboard
#  id: BoxAgrichem
#  description: For the budding botanist ready to learn about maximizing farm output. This faded box must be at least 50 years old.
#  components:
#  - type: StorageFill
#    contents:
#    - id: PaperAgrichemManual
#    - id: ChemistryEmptyBottle01
#    - id: PotassiumChemistryBottle
#    - id: PhosphorusChemistryBottle
#    - id: NitrogenChemistryBottle
#    - id: HydrogenChemistryBottle
#    - id: EthanolChemistryBottle
#    - id: RadiumChemistryVial
#    - id: ChlorineChemistryVial
#  - type: Sprite
#    layers:
#      - state: boxwide
#      - state: agrichemkit
#  - type: GuideHelp
#    guides:
#    - Botanical
#    - Chemicals
