- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  requirements:
  # WD EDIT START
  # - !type:CharacterDepartmentTimeRequirement
  #   department: Engineering
  #   min: 36000
  # WD EDIT END
  - !type:CharacterEmployerRequirement
    employers:
    - HephaestusIndustries
    - EinsteinEngines
    - NanoTrasen
  # WD EDIT START
  - !type:CharacterOverallTimeRequirement
    min: 3600
  # WD EDIT END
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: AtmosphericTechnicianGear
  subGear:
  - AtmosphericTechnicianPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAtmos
    back: ClothingBackpackAtmospherics
    shoes: ClothingShoesBootsWorkAtmos # WWDP edit (spaceman)
    id: AtmosPDA
    ears: ClothingHeadsetEngineering

- type: startingGear
  id: AtmosphericTechnicianPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitAtmos
    head: ClothingHeadEnvirohelmAtmos
    gloves: ClothingHandsGlovesEnviroglovesAtmos
