- type: entity
  name: barrier grenade box
  parent: BoxSteel
  id: BoxGrenadeBarrier
  description: A box full of barrier grenades.
  components:
  - type: StorageFill
    contents:
      - id: GrenadeBarrier
        amount: 4
  - type: Sprite
    layers:
    - state: box_steel_rib_base
    - state: bg
      map: [ paper ]
      sprite: _White/Objects/Storage/boxes_icon.rsi
    - state: flashbang
      map: [ label ]
      sprite: _White/Objects/Storage/boxes_icon.rsi
    - state: box_steel_sec
      map: [ top ]
  - type: GenericVisualizer
    visuals:
      enum.StorageVisuals.Open:
        base:
          True: { state: box_steel_sec_open }
          False: { state: box_steel_sec }
