- type: department
  id: Logistics
  name: department-Logistics
  description: department-Cargo-description
  color: "#A46106"
  # Orion-Start
  weight: -5
  # Orion-End
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - MailCarrier

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  # Orion-Start
  weight: -4
  # Orion-End
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  - MartialArtist
  # - Prisoner - WD EDIT: Moved to Security
  - Gladiator
  - Hobo # WD EDIT

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  # Orion-Start
  weight: -1
  # Orion-End
  roles:
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  editorHidden: true
#  weight: 120 # Orion-Edit: Moved

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  # Orion-Start
  weight: -2
  # Orion-End
  roles:
  - Captain
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - ChiefJustice
  - AdministrativeAssistant
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - Maid # WD EDIT
  primary: false
#  weight: 100 # Orion-Edit: Moved

# WD EDIT START
# - type: department
#   id: Dignitary
#   name: department-Dignitary
#   description: department-Dignitary-description
#   color: "#33FE6D"
#   roles:
#   - BlueshieldOfficer
#   - NanotrasenRepresentative
#   - Magistrate
#   primary: false
#   weight: 101
# WD EDIT END

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  # Orion-Start
  weight: -6
  # Orion-End
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  # Orion-Start
  weight: -7
  # Orion-End
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - SeniorPhysician
  - MedicalBorg

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#DE3A3A"
  # Orion-Start
  weight: -3
  # Orion-End
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - SeniorOfficer
  - Detective
  - Warden
  - PrisonGuard
  - Brigmedic
  - Prisoner # WD EDIT: Moved from Civilian

- type: department
  id: Epistemics
  name: department-Epistemics
  description: department-Science-description
  color: "#D381C9"
  # Orion-Start
  weight: -8
  # Orion-End
  roles:
  - ResearchDirector
  - SeniorResearcher
  - Scientist
  - ResearchAssistant
  - Chaplain
  - ForensicMantis
  - Librarian
  - Roboticist

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  # Orion-Start
  weight: -9
  # Orion-End
  roles:
  - Borg
  - StationAi

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#29282f"
  # Orion-Start
  weight: -42
  # Orion-End
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  primary: false
