- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 7200 #DeltaV 2 hours
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Theatre # DeltaV - Add Theatre access
  - Reporter # DeltaV - Add Reporter access

- type: startingGear
  id: ReporterGear
  subGear:
  - ReporterPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitReporter
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
    pocket2: CandyBucket
  innerClothingSkirt: ClothingUniformJumpsuitJournalist
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: ReporterPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitReporter
    head: ClothingHeadEnvirohelmReporter
    gloves: ClothingHandsGlovesEnviroglovesReporter
