# No idea why it's in sci but we ball.
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: PositronicBrain # WD EDIT: StationAiBrain -> PositronicBrain
  jobPreviewEntity: PlayerStationAiPreview
  nameDataset: NamesAI
  applyTraits: false
  spawnLoadout: false
  canHavePassport: false
  requirements:
  - !type:CharacterOverallTimeRequirement # WWDP
    min: 7200
  special: # WWDP random lawset
  - !type:AddComponentSpecial
    components:
    - type: RandomizeStartingLawset
      lawsets:
      - Asimov
      - Augustine
      - Crewsimov
      - Corporate
      - NTDefault
      - NTAgressive
      - EfficiencyLawset

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgBattery
  applyTraits: false
  canHavePassport: false
