- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
    - id: FlashlightSeclite
    # - id: WeaponDisabler - WD EDIT
    - id: ClothingBeltSecurityFilled
    - id: ClothingHandsGlovesKravMaga # Goobstation - Martial Arts
    - id: Flash
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHeadsetAltSecurity
    # - id: ClothingHandsGlovesCombat - WD EDIT
    - id: ClothingShoesBootsJack
    - id: ClothingOuterCoatWarden
    - id: ClothingOuterWinterWarden
    - id: RubberStampWarden
    - id: DoorRemoteArmory
    - id: ClothingOuterHardsuitCombatWarden # WD EDIT: ClothingOuterHardsuitCombatWarden -> ClothingOuterHardsuitWarden
    - id: HoloprojectorSecurity
    # - id: ClothingEyesHudSecurity - WD EDIT
    - id: BoxPDAPrisoner # Delta-V
    - id: ClothingShoesBootsWinterWarden #Delta V: Add departmental winter boots
    - id: BoxEncryptionKeyPrisoner #Delta-V
    - id: BoxPrisonerHeadset
    - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
      prob: 0.3
    # WD EDIT START
    - id: BoxBasicRegulatorLampBig
    - id: BoxBodyBagPrisoner
    - id: ClothingMaskGasSecurity
    # WD EDIT END

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
    - id: FlashlightSeclite
    # - id: WeaponDisabler - WD EDIT
    - id: ClothingBeltSecurityFilled
    - id: ClothingHandsGlovesKravMaga # Goobstation - Martial Arts
    - id: Flash
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHeadsetAltSecurity
      # - id: ClothingHandsGlovesCombat # WWDP
    - id: ClothingShoesBootsJack
    - id: ClothingOuterCoatWarden
    - id: ClothingOuterWinterWarden
    - id: RubberStampWarden
    - id: DoorRemoteArmory
    - id: HoloprojectorSecurity
    # - id: ClothingEyesHudSecurity - WD EDIT
    - id: BoxPDAPrisoner # Delta-V
    - id: ClothingShoesBootsWinterWarden #Delta V: Add departmental winter boots
    - id: BoxEncryptionKeyPrisoner #Delta-V
    - id: BoxPrisonerHeadset
    - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
      prob: 0.3
    # WD EDIT START
    - id: BoxBasicRegulatorLampBig
    - id: BoxBodyBagPrisoner
    - id: ClothingMaskGasSecurity
    # WD EDIT END

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
    - id: FlashlightSeclite
      prob: 0.8
    # - id: WeaponDisabler - WD EDIT
    - id: ClothingUniformJumpsuitSec # WD - Less random bloat
    - id: ClothingHeadHelmetBasic
    # - id: ClothingHeadHelmetInsulated - WD EDIT
    #   prob: 0.4
    - id: ClothingOuterArmorBasic # WD EDIT
    - id: ClothingBeltSecurityFilled
    # - id: ClothingBeltCorporateJudo - WD EDIT
    - id: Flash
      prob: 0.5
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHeadsetAltSecurityRegular # Goobstation
    - id: ClothingHandsGlovesColorBlack
    - id: ClothingShoesBootsJack
    - id: WeaponMeleeNeedle
      prob: 0.1
    # - id: ClothingEyesHudSecurity - WD EDIT
    - id: HoloprojectorSecurity
      prob: 0.6
    - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
      prob: 0.3
    - id: ClothingMaskGasSecurity # WWDP

- type: entity
  id: LockerBrigmedicFilled
  suffix: Corpsman, Filled # DeltaV - rename brigmedic to corpsman
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesGlassesCorpsman # DeltaV - Corpsman Glasses
    # - id: WeaponDisabler - WD EDIT
    - id: TrackingImplanter
      amount: 2
    ##      - id: ClothingOuterHardsuitCombatCorpsman # DeltaV - ClothingOuterHardsuitBrigmedic replaced in favour of corpsman's combat hardsuit; removing from standard filled locker to place in hardsuit filled locker.
    - id: BoxSterileMask
    - id: ClothingHeadHatBeretCorpsman # DeltaV - ClothingHeadHatBeretBrigmedic replaced in favour of corpsman beret.
    ##      - id: ClothingOuterCoatAMG # DeltaV - removed until I can resprite it or replace it.
    - id: ClothingUniformJumpsuitBrigmedic
    - id: ClothingUniformJumpskirtBrigmedic
    ##      - id: ClothingUniformJumpskirtOfLife # DeltaV - nah
    ##        prob: 0.1
    - id: HandheldGPSBasic # Delta V - added it for tracking the implant tracker pop up.
    - id: MedkitFilled
    - id: MedkitCombatFilled
      prob: 0.6
    - id: MedkitAdvancedFilled
      prob: 0.4
    - id: MedkitOxygenFilled
      prob: 0.3
    - id: MedkitBruteFilled
      prob: 0.3
    - id: MedkitToxinFilled
      prob: 0.3
    - id: MedkitBurnFilled
      prob: 0.7
    ##      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse # DeltaV - why
    ##        prob: 0.15
    - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
      prob: 0.3
    # WD EDIT START
    - id: ClothingHandsGlovesNitrile
    - id: ClothingBeltCorpsmanWebbing
    - id: FieldSurgeryKit
    - id: DefibrillatorCompact
    - id: BoxBodyBagPrisoner
    - id: ClothingMaskGasSecurity
    # W EDIT END

# DeltaV - adding corpsman locker w/ hardsuit

- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Corpsman, Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesGlassesCorpsman # DeltaV - Corpsman Glasses
    # - id: WeaponDisabler - WD EDIT
    - id: TrackingImplanter
      amount: 2
    - id: ClothingOuterHardsuitBrigmedic # WD EDIT: ClothingOuterHardsuitCombatCorpsman -> ClothingOuterHardsuitBrigmedic
    - id: ClothingUniformJumpsuitBrigmedic
    - id: ClothingUniformJumpskirtBrigmedic
    - id: HandheldGPSBasic # Added GPS because I just think it should be there tbh.
    - id: MedkitFilled
    - id: MedkitCombatFilled
      prob: 0.6
    - id: MedkitAdvancedFilled
      prob: 0.4
    - id: MedkitOxygenFilled
      prob: 0.3
    - id: MedkitBruteFilled
      prob: 0.3
    - id: MedkitToxinFilled
      prob: 0.3
    - id: MedkitBurnFilled
      prob: 0.7
    - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
      prob: 0.3
    # WD EDIT START
    - id: ClothingHandsGlovesNitrile
    - id: ClothingBeltCorpsmanWebbing
    - id: FieldSurgeryKit
    - id: DefibrillatorCompact
    - id: BoxBodyBagPrisoner
    - id: ClothingMaskGasSecurity
    - id: OxygenTankFilled
    # WD EDIT END

# DeltaV - end addition

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesHudSecurity # WD EDIT: ClothingEyesHudSecurity -> ClothingEyesGlassesSecurity
    - id: ClothingHeadHatFedoraBrown
    - id: ClothingNeckTieDet
    - id: ClothingOuterVestDetective
    - id: ClothingOuterCoatDetective
    - id: FlashlightSeclite
    - id: ForensicScanner
    - id: LogProbeCartridge
    - id: BoxForensicPad
    - id: DrinkDetFlask
    - id: ClothingHandsGlovesForensic
    - id: RubberStampDetective
    - id: HoloprojectorSecurity
    - id: BoxEvidenceMarkers
    - id: BoxTapeRecorder # DeltaV
    - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
      prob: 0.3
    - id: ClothingMaskGasSecurity # WWDP

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
    - id: ClothingHeadHelmetBombSuit
    - id: ClothingOuterSuitBomb
    # NT is cheap, what can you do...
    - id: Wirecutter
      prob: 0.9
    - id: Screwdriver
      prob: 0.9
    - id: Multitool
      prob: 0.5

- type: entity
  parent: GunSafe
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: GunSafe
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: [GunSafe, AlertLevelLock] # WWDP
  id: GunSafeRifleLecter
  name: lecter safe
  suffix: Alert Level Lock # WWDP
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: [GunSafe, AlertLevelLock] # WWDP
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  suffix: Alert Level Lock # WWDP
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: [GunSafe, AlertLevelLock] # WWDP
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  suffix: Alert Level Lock # WWDP
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  parent: [GunSafe, AlertLevelLock] # WWDP
  id: GunSafeShotgunKammerer
  name: kammerer safe
  suffix: Alert Level Lock # WWDP
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  parent: [GunSafe, AlertLevelLock] # WWDP
  name: wt550 safe
  suffix: Alert Level Lock # WWDP
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: [GunSafe, AlertLevelLock] # WWDP
  id: GunSafeLaserCarbine
  name: laser safe
  suffix: Alert Level Lock # WWDP
  components:
  - type: StorageFill
    contents:
    - id: WeaponLaserCarbine
      amount: 3

- type: entity
  id: GunSafeRifleBRDIR25
  suffix: Alert Level Lock # WWDP
  parent: [GunSafe, AlertLevelLock] # WWDP
  name: BRDI-R25 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunBRDIR25
      amount: 2
    - id: MagazineCaselessRifle
      amount: 4
